config/routes.rb
Rails.application.routes.draw do
  devise_for :purchasers
  devise_for :admins
  resource :admin, only: [:show], controller: :admin
  resource :cart, only: [:show, :destroy, :create] do
    get "checkout", on: :collection, to: "carts#checkout"
  end
  get "registrations/new"
  get "registrations/create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "new" => "products#new"

  get "/registro"=>"registrations#new", as: "registro"
    # post "/registro" => "registrations#create"

    # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
    # Can be used by load balancers and uptime monitors to verify that the app is live.
    # get "up" => "rails/health#show", as: :rails_health_check
    # post 'products', to:'products#create'
    # get '/new', to: 'products#new', as: :new_product
    # get '/', to: 'products#index', as: :products
    # get '/:id', to: 'products#show', as: :product

    resources :favorites, only: [:index, :create, :destroy]

    resources :products
    get '/login_selection', to: 'sessions#selection', as: 'login_selection'

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "products#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :purchaser, optional: true
    before_create :set_secret_id
    has_many :cart_items, dependent: :destroy
    has_many :products, through: :cart_items

    private
    
    def set_secret_id
        self.secret_id = SecureRandom.uuid + DateTime.now.to_i.to_s
    end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :product
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :product
  belongs_to :purchaser

  validates :product_id, uniqueness: { scope: :purchaser_id }
end

app/models/product.rb
class Product < ApplicationRecord
    ORDENAR_POR = {
        mas_recientes: "created_at DESC",
        mas_antiguos: "created_at ASC",
        menor_precio: "precio ASC",
        mayor_precio: "precio DESC"
    }


    validates :nombre, presence: true
    validates :descripcion, presence: true
    validates :precio, presence: true
    validates :imagen, presence: true
    has_many :cart_items
    has_many :favorites, dependent: :destroy
end

app/models/purchaser.rb
class Purchaser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :carts
  has_many :favorites
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    before_action :check_admin
    def show
        @products = Product.all
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :set_current_cart
  def after_sign_in_path_for(resource)
    if resource.is_a?(Admin)
      admin_path 
    elsif resource.is_a?(Purchaser)
      products_path  
    else
      super  
    end
  end
  protected
  def check_admin
    if !current_admin
        redirect_to :products
    end
  end

  private
  
  def set_current_cart
    if session[:current_cart_id]
      @current_cart = Cart.find_by_secret_id(session[:current_cart_id])
      if current_purchaser && !@current_cart.purchaser
        @current_cart.update(purchaser_id: current_purchaser.id)
      end
    else
      if current_purchaser && current_purchaser.carts.any?
        @current_cart = current_purchaser.carts.last
        session[:current_cart_id] = @current_cart.secret_id
      end
    end 
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    before_action :set_product, only: [:create, :destroy]
    def create
        if !@current_cart
            @current_cart = Cart.create
            session[:current_cart_id] = @current_cart.secret_id
        end
        @current_cart.cart_items.create(product_id: params[:product_id])
        redirect_to :products
    end
    def show
        
    end
    def checkout 
        if @current_cart&.cart_items&.any?
            session[:current_cart_id] = nil
            @current_cart.cart_items.destroy_all
            redirect_to :products, notice: 'Compra realizada con exito! Gracias!'
        else
            redirect_to :products, notice: 'No hay productos en el carrito!'
        end   
    end

    def destroy
        @cart_item = @current_cart&.cart_items&.find_by_product_id(@product.id)
        @cart_item.destroy
        redirect_to cart_path(@current_cart)
    end
    
    private 
    
    def set_product
        @product = Product.find(params[:product_id])
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :require_login

  def index
    @favorites = current_purchaser.favorites.includes(:product)
  end

  def create
    @favorite = current_purchaser.favorites.new(favorite_params)

    if @favorite.save
      redirect_to @favorite.product
    else
      redirect_to products_path, alert: 'No se pudo añadir a favoritos.'
    end
  end

  def destroy
    @favorite = current_purchaser.favorites.find(params[:id])
    @favorite.destroy
    redirect_to request.referrer || products_path
  end

  private

  def favorite_params
    params.require(:favorite).permit(:product_id)
  end

  def require_login
    unless purchaser_signed_in?
      flash[:alert] = 'Debes iniciar sesión para añadir productos a tus favoritos.'
      redirect_to request.referrer || products_path
    end
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :check_admin, except: ["index", "show"]
    def index
        @products = Product.all.paginate(page: params[:page], per_page: 10)

        ordenar_por = Product::ORDENAR_POR.fetch(params[:ordenar_por]&.to_sym, Product::ORDENAR_POR[:mas_recientes])
        
        @products = @products.order(ordenar_por)
    end

    def show
        @product = Product.find(params[:id])
    end

    def new
        @product = Product.new
    end

    def create
        @product = Product.new(product_params) 
        if @product.save
            redirect_to products_path, notice: 'Tu producto ha sido agregado correctamente al catalogo!'
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to products_path, notice: 'Tu producto ha sido actualizado!'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @product = Product.find(params[:id])
        @product.destroy
         redirect_to products_path, notice: 'Tu producto ha sido eliminado correctamente!'
    end
    private

    def product_params
        params.require(:product).permit(:nombre, :descripcion, :precio, :imagen)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  layout "registro", only: [ :new ]
  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def sessions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/admin/show.html.erb
<h1> Pagina de administrador </h2>
<div class="link-container">
    <%= link_to 'Agregar Producto', new_product_path, class: 'add-product' %>
</div>
<div class="product_content">
    <% @products.each do |product| %>
        <div id="products" class="product_card">
            <%= link_to product_path(product.id), class: 'product' do %>
                <img class="product_image" src=<%=product.imagen %> alt=<%=product.descripcion %> width="250" height="250">
                <h2 class="product_title"> <%= product.nombre %></h2>
                <span class="product_price">$ <%= product.precio %></span>
            <% end %>
        </div>
    <% end %>
</div>

app/views/carrusel/_productos.html.erb
<h2 class="products-title">Productos Destacados</h2>
<div class="products-list">
  <div class="products-list-wrapper">
  <% productos = [
        { nombre: "Celular", descripcion: "Última tecnología", imagen: "iphone15.jpeg" },
        { nombre: "Perfume", descripcion: "Fragancia exclusiva", imagen: "phantom.jpeg" },
        { nombre: "Computadora", descripcion: "Alta potencia", imagen: "macbook.jpeg" },
        { nombre: "Celular", descripcion: "Última tecnología", imagen: "iphone15.jpeg" },
        { nombre: "Perfume", descripcion: "Fragancia exclusiva", imagen: "phantom.jpeg" },
        { nombre: "Computadora", descripcion: "Alta potencia", imagen: "macbook.jpeg" }
      ] %>
  
      <% productos.each do |producto| %>
  <%= render partial: "shared/producto_destacado", locals: { producto: producto } %>
  <% end %>
</div>
</div>

app/views/carts/show.html.erb
<div class='cart'>
    <h1 class="cart_title"> Carrito de compras </h1>
    <% if @current_cart&.products&.any? %>
        <% @current_cart.products.each do |product| %>
            <div class= "cart_card">
                <p class="product_name"><%= product.nombre %></p>
                <p class="product_price"><%= number_to_currency product.precio %></p>
                <%= link_to "Eliminar", cart_path(product_id: product.id), class:"cart_button", data: {turbo_method: "delete"} %>
            </div>
        <% end %>   
    <% end %>
    <p class="cart_total"> Total: $<%= @current_cart&.products&.sum(&:precio) %> </p>
    <div class= "cart_checkout">
        <% if @current_cart&.cart_items&.any? %>
            <p class="cart_subtitle"> Hay <%= @current_cart.cart_items.count %> productos en el carrito. </p>
            <% if @current_cart&.cart_items&.any? %>
                <%= link_to "Comprar", checkout_cart_path, class:"cart_button" %>
            <% else %>
                <%= content_tag :div, "Comprar", class:"cart_button" %>
            <% end %>
        <% else %>
            <p> No hay productos en el carrito. </p>
        <% end %>
    </div>
    <% if !@current_purchaser %>
        <%= link_to "Iniciar sesion para guardar el carrito", new_purchaser_session_path, class: 'iniciar_sesion_cart' %>
    <% end %>
</div>

app/views/favorites/index.html.erb
<div class='cart'>
  <h1 class="cart_title">Favoritos</h1>

  <% @favorites.each do |favorite| %>
    <div class="cart_card">
      <p class="product_name"><%= favorite.product.nombre %></p>
      <p class="product_price"><%= number_to_currency favorite.product.precio %></p>
      <%= link_to 'Ver Producto', product_path(favorite.product), class: 'cart_button' %>
      <%= link_to "Eliminar", favorite_path(favorite), class: "cart_button", data: { turbo_method: "delete" } %>
    </div>
  <% end %>

  <% if @favorites.empty? %>
    <p>No tienes productos marcados como favoritos.</p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Tp Codemasters Ruby" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="body">  
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <main class="main">
      <%= yield %>   
    </main>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Login</title>
<%= stylesheet_link_tag "login", "data-turbo-track": "reload" %>
<%= javascript_importmap_tags %>
</head>
<body>
<div class="loggin-container">
<div class="page-name">
  <%= link_to products_path, class: 'page-link' do %>
    <h1>CODE-MARKET</h1>
  <% end %>
</div>
<h1>Login</h1>
<%= form_with url: login_path, method: :post, local: true do |form| %>
<div class="text-area-container">
<%= form.label :username, "Nombre de Usuario" %>    
<%= form.text_field :username, required: true, class:"nombre-usuario"%>
<%= form.label :password, "Contraseña" %>
<%= form.password_field :password, required: true, class:"contrasenia"%>
</div>
<div>
<%= form.submit "Ingresar" %>
</div>
<% end %>
 
        <!-- Enlace a la ruta de registro -->
<div class="register-link">
<p>¿No tienes cuenta? <%= link_to "Regístrate", "/registro" %></p>
</div>
</div>    
</body>
</html>

app/views/layouts/registro.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= stylesheet_link_tag 'registro', media: 'all' %>
  <title>Página de Registro</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body>
  <h1>PÁGINA DE REGISTRO</h1>
  <%= yield %>
</body>
</html>

app/views/products/_add_to_cart.html.erb
<% if @current_cart && @current_cart.products.where(id: @product.id).any? %>
    <span> Ya se encuentra en el carrito </span>
<% else %>
    <%= link_to "Agregar al carrito", cart_path(product_id: @product.id), class: 'add-favorites',  data: { turbo_method: "post" } %>
<% end %>

app/views/products/edit.html.erb
<h1> Editar Producto </h1>

<%= form_with model: @product, class: "form-container" do |form| %>
    <div class="error-messages">
        <%= @product.errors.full_messages.each do |error| %>
            <div class="error-message">
                <%= error %>
            </div>
        <% end %>
    </div>

    <div class="form-group">
        <%= form.label :nombre, class: "form-label" %>
        <%= form.text_field :nombre, class: "form-input" %>
    </div>

    <div class="form-group">
        <%= form.label :descripcion, class: "form-label" %>
        <%= form.text_area :descripcion, class: "form-textarea" %>
    </div>

    <div class="form-group">
        <%= form.label :precio, class: "form-label" %>
        <%= form.number_field :precio, class: "form-input" %>
    </div>

    <div class="form-group">
        <%= form.label :imagen, class: "form-label" %>
        <%= form.text_field :imagen, class: "form-input" %>
    </div>

    <div class="form-group">
        <%= form.submit "Guardar Producto", class: "form-submit" %>
    </div>
<% end %>

<style>
  .form-container {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f9f9f9;
    border: 1px solid #ddd;
    border-radius: 8px;
  }

  .error-messages {
    color: #d9534f;
    margin-bottom: 15px;
  }

  .error-message {
    font-size: 0.9em;
    margin-bottom: 5px;
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
  }

  .form-input, .form-textarea {
    width: 100%;
    padding: 8px;
    font-size: 1em;
    border: 1px solid #ccc;
    border-radius: 4px;
  }

  .form-textarea {
    height: 100px;
  }

  .form-submit {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 1em;
    background-color: #5cb85c;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-submit:hover {
    background-color: #4cae4c;
  }
</style>

app/views/products/index.html.erb
<h1 class="products-title"> Productos </h1>


<%= form_with url: products_path, method: :get, local: true, class: 'order-form' do |form| %>
  <div class="order-form-container">
    <label for="ordenar_por">Ordenar por:</label>
    <%= form.select :ordenar_por, 
      options_for_select(Product::ORDENAR_POR.keys.map { |key| [key.to_s.humanize.titleize, key] }, params[:ordenar_por]), 
      {}, 
      class: 'order-select', id: 'ordenar_por' %>
    <%= form.submit 'Ordenar', class: 'order-button' %>
  </div>
<% end %>

<div class="product_content">

    <% @products.each do |product| %>
        <div id="products" class="product_card">
            <%= link_to product_path(product.id), class: 'product' do %>
                <img class="product_image" src=<%=product.imagen %> alt=<%=product.descripcion %> width="250" height="250">
                <h2 class="product_title"> <%= product.nombre %></h2>
                <span class="product_price">$ <%= product.precio %></span>
            <% end %>
        </div>
    <% end %>
</div>

<%= will_paginate @products, previous_label: 'Anterior', next_label: 'Siguiente', previous_disabled_class: 'disabled', next_disabled_class: @products.next_page ? nil : 'disabled' %>  

app/views/products/new.html.erb
<h1> Agregar Producto </h1>

<%= form_with model: @product, class: "form-container" do |form| %>
    <div class="error-messages">
        <%= @product.errors.full_messages.each do |error| %>
            <div class="error-message">
                <%= error %>
            </div>
        <% end %>
    </div>

    <div class="form-group">
        <%= form.label :nombre, class: "form-label" %>
        <%= form.text_field :nombre, class: "form-input" %>
    </div>

    <div class="form-group">
        <%= form.label :descripcion, class: "form-label" %>
        <%= form.text_area :descripcion, class: "form-textarea" %>
    </div>

    <div class="form-group">
        <%= form.label :precio, class: "form-label" %>
        <%= form.number_field :precio, class: "form-input" %>
    </div>

    <div class="form-group">
        <%= form.label :imagen, class: "form-label" %>
        <%= form.text_field :imagen, class: "form-input" %>
    </div>

    <div class="form-group">
        <%= form.submit "Guardar Producto", class: "form-submit" %>
    </div>
<% end %>

<style>
  .form-container {
    max-width: 400px;
    margin: 0 auto;
    padding: 20px;
    background-color: #f9f9f9;
    border: 1px solid #ddd;
    border-radius: 8px;
  }

  .error-messages {
    color: #d9534f;
    margin-bottom: 15px;
  }

  .error-message {
    font-size: 0.9em;
    margin-bottom: 5px;
  }

  .form-group {
    margin-bottom: 15px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
  }

  .form-input, .form-textarea {
    width: 100%;
    padding: 8px;
    font-size: 1em;
    border: 1px solid #ccc;
    border-radius: 4px;
  }

  .form-textarea {
    height: 100px;
  }

  .form-submit {
    display: block;
    width: 100%;
    padding: 10px;
    font-size: 1em;
    background-color: #5cb85c;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .form-submit:hover {
    background-color: #4cae4c;
  }
</style>

app/views/products/show.html.erb
<div class="link-container">
  <% if !current_admin %>
    <%= link_to 'Volver', :products, class: 'add-product-cart' %>
  <% else %>
      <%= link_to 'Volver', :admin, class: 'add-product-cart' %>
  <% end %>
</div>
<div class="product_detail_container">
  <div class="product_detail_img_container">
    <img src="<%= @product.imagen %>" alt="<%= @product.descripcion %>" width="250" height="250">
  </div>
  <div class="product_detail_info">
    <h2> <%=@product.nombre %> </h2>
    <h4 class="product_price"> Precio:<span class="product_price_span"> $<%= @product.precio %> </span></h2>
    <p><strong>Descripción:</strong> <%= @product.descripcion %></p>
    <% if current_admin %> 
      <p><%= link_to 'Editar Producto', edit_product_path(@product.id), class: 'abm-product' %></p>
      <p><%= link_to 'Eliminar Producto', product_path(@product.id), class: 'abm-product', data: { turbo_method: :delete, turbo_confirm: '¿Está seguro que desea eliminar este producto?' } %></p>
    <% end %>
  </div>
</div>
<% if !current_admin %> 
  <div class="product_detail_footer">
      <div class="link-container">
          <% if purchaser_signed_in? and current_purchaser.favorites.exists?(product: @product) %>
            <%= link_to 'Eliminar de Favoritos', favorite_path(current_purchaser.favorites.find_by(product: @product)), data: { turbo_method: :delete }, class: 'add-favorites'%>
          <% else %>
            <%= link_to 'Añadir a Favoritos', favorites_path(favorite: { product_id: @product.id }), data: { turbo_method: :post }, class: 'add-favorites'%>
          <% end %>
      </div>
      <div class="link-container">
        <%= render "add_to_cart", product: @product %>
      </div>
  </div>
<% end %>

app/views/shared/_flash.html.erb
<%= notice %>

<%= alert %>

app/views/shared/_header.html.erb
<div class="header">
  <% if !current_admin %>
    <%= link_to products_path do %>
      <h1 class="page-name">CODE-MARKET</h1>
    <% end %>
  <% else %>
    <%= link_to admin_path do %>
      <h1 class="page-name">CODE-MARKET</h1>
    <% end %>
  <% end %>
<% if !current_admin %>
  <div class="link-container">
    <%= link_to 'Favoritos', '/favorites' %>
  </div>

  <%= link_to cart_path do %>
    <div class="link-container-cart">
      <%= image_tag("carrito-de-compras.png") %>
      <% if @current_cart && @current_cart.cart_items.any? %>
        <span class="span_carrito">
          <%= @current_cart.cart_items.count %>
        </span>
      <% end %>
    </div>
  <% end %>
<% end %>

  <div class="link-container">
    <% if !current_admin %>
      <% if current_purchaser %>
        <%= link_to 'Cerrar Sesion', destroy_purchaser_session_path, data: {turbo_method: :delete} %>
      <% else %>
        <%= link_to 'Iniciar Sesion', login_selection_path %>
        <%= link_to 'Registro', new_purchaser_registration_path %>
      <% end %>
    <%else%>
    <%= link_to 'Cerrar Sesion', destroy_admin_session_path, data: {turbo_method: :delete} %>
    <%end%>
  </div>
</div>

app/views/shared/_producto_destacado.html.erb
<div class="product-card">
    <img src="<%= image_path(producto[:imagen]) %>" alt="<%= producto[:nombre] %>">
    <h3><%= producto[:nombre] %></h3>
    <p><%= producto[:descripcion] %></p>
    <button>Ver mas</button>
</div>